### ISSUE TITLE
Getting import error: "cannot import name 'prepare_test_plan'"

### ISSUE THREAD

**Issue by yasin-gorgij** [innogames/ltc#18]
When I run the command `./manage makemigrations` I get this error: `ImportError: cannot import name 'prepare_test_plan'`. Changing line 21 of `controller/views/provision.py` to `from controller.views.controller_views.py import prepare_test_plan` solves the problem. I'm not sure whether it's a bug or not.

**Comment by v0devil** [comment]
Thanks! Fixed here https://github.com/innogames/JMeter-Control-Center/commit/6f75d3cae92dcf21bc30b34624d46477ce317e8e
