### ISSUE TITLE
Expected axis has 16 elements, new values have 8 elements

### ISSUE THREAD

**Issue by TioLuiso** [innogames/ltc#19]
Hiya peoples

First of all, thanks a lot for your product, it looks really interesting. I have built a docker-compose to deploy your solution quickly. If you're interested, it's here: https://github.com/arcmedia/JmeterControlCenter

I have been trying to use your project to analyse the results of JMeter execution runs.

I updated the csv file to be compliant with your specification, reordering and renaming the columns. The columns that I have are like follows:

`timestamp,response_time,url,responseCode,success,label,responseMessage,threadName,dataType,failureMessage,bytes,sentBytes,grpThreads,allThreads,Latency,IdleTime,Connect`

I try to upload it, but when I do, I see an error like this

Request Method: | POST
-- | --
http://localhost:8888/analyzer/upload/test_result_file/
1.11.16
ValueError
Length mismatch: Expected axis has 16 elements, new values have 8 elements
/usr/local/lib/python3.6/site-packages/pandas/core/internals/managers.py in set_axis, line 155
/usr/local/bin/python
3.6.8
['/JMeter-Control-Center',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
Mon, 11 Mar 2019 09:56:31 +0000

![image](https://user-images.githubusercontent.com/8038949/54115266-72455500-43ec-11e9-878d-4b7e7dd64883.png)

**Comment by v0devil** [comment]
Hi! Can you plz provide few lines from your file to test

**Comment by TioLuiso** [comment]
Indeed. Here you have 20 rows plus header
[products_Excerpt.zip](https://github.com/innogames/JMeter-Control-Center/files/2952892/products_Excerpt.zip)

And thanks a lot

**Comment by v0devil** [comment]
Ok sorry for delay, i will check it now

**Comment by v0devil** [comment]
Hey, thanks for docker btw, it`s awesome, I made some fixes to parse your file
https://github.com/innogames/JMeter-Control-Center/commit/bacef15205e9884e1940f2a2cc06e71ba53a0495
You have to execute also makemigrations/migrate since it applies some changes in the schema.
To parse your file I did put those columns to CSV file fields:
response_time,url,responseCode,success,label,responseMessage,threadName,dataType,failureMessage,bytes,sentBytes,grpThreads,allThreads,Latency,IdleTime,Connect (without timestamp).
Looking forward for your ideas on how to improve this thing !

**Comment by TioLuiso** [comment]
Nice!!!!
Now it doesn't explode, but looks like it takes its time to process a 48Mb file.
I would love to contribute, but don't know python at all. I'm a dotnetter.
Anyway, if you need to integrate your product with docker, and publish images, I can try to help
BTW: Is there any way to enable authentication?
Thanks a huge lot

**Comment by SrinivasanGuna** [comment]
Hi, Can anyone please give me the curl command to upload test results. I got stuck in the csv_file parameter.
